/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "remote_fifo.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include "remote_fifo_server_instance.h"

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

// declare init function
void server_rf_init();


int main (int argc, char **argv)
{
	register SVCXPRT *transp;

	server_rf_init();
	run_rf_server();
	/*
	pmap_unset (REMOTE_FIFO, SERVER_API);
	pmap_unset (REMOTE_FIFO, CLIENT_API);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, REMOTE_FIFO, SERVER_API, remote_fifo_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (REMOTE_FIFO, SERVER_API, udp).");
		exit(1);
	}
	if (!svc_register(transp, REMOTE_FIFO, CLIENT_API, remote_fifo_101, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (REMOTE_FIFO, CLIENT_API, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, REMOTE_FIFO, SERVER_API, remote_fifo_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (REMOTE_FIFO, SERVER_API, tcp).");
		exit(1);
	}
	if (!svc_register(transp, REMOTE_FIFO, CLIENT_API, remote_fifo_101, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (REMOTE_FIFO, CLIENT_API, tcp).");
		exit(1);
	}

	svc_run ();
	*/
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
