/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "remote_fifo.h"

bool_t
xdr_management_rf (XDR *xdrs, management_rf *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->callback.callback_val, (u_int *) &objp->callback.callback_len, ~0))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->uid))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_data_rf (XDR *xdrs, data_rf *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->descriptor))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->buf.buf_val, (u_int *) &objp->buf.buf_len, ~0,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->callback.callback_val, (u_int *) &objp->callback.callback_len, ~0))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->uid))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_management_rf_res (XDR *xdrs, management_rf_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->code))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->callback.callback_val, (u_int *) &objp->callback.callback_len, ~0))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_data_rf_res (XDR *xdrs, data_rf_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->descriptor))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->code))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->buf.buf_val, (u_int *) &objp->buf.buf_len, ~0,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->callback.callback_val, (u_int *) &objp->callback.callback_len, ~0))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0))
		 return FALSE;
	return TRUE;
}
