/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "remote_fifo.h"


void
remote_fifo_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	management_rf  create_rf_1_arg;
	enum clnt_stat retval_2;
	int result_2;
	management_rf  unlik_rf_1_arg;
	enum clnt_stat retval_3;
	int result_3;
	management_rf  open_rf_1_arg;
	enum clnt_stat retval_4;
	int result_4;
	management_rf  close_rf_1_arg;
	enum clnt_stat retval_5;
	int result_5;
	data_rf  write_rf_1_arg;
	enum clnt_stat retval_6;
	int result_6;
	data_rf  read_rf_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, REMOTE_FIFO, SERVER_API, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = create_rf_1(&create_rf_1_arg, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = unlik_rf_1(&unlik_rf_1_arg, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = open_rf_1(&open_rf_1_arg, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_4 = close_rf_1(&close_rf_1_arg, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_5 = write_rf_1(&write_rf_1_arg, &result_5, clnt);
	if (retval_5 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_6 = read_rf_1(&read_rf_1_arg, &result_6, clnt);
	if (retval_6 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
remote_fifo_101(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	management_rf_res  create_rf_res_101_arg;
	enum clnt_stat retval_2;
	int result_2;
	management_rf_res  unlik_rf_res_101_arg;
	enum clnt_stat retval_3;
	int result_3;
	management_rf_res  open_rf_res_101_arg;
	enum clnt_stat retval_4;
	int result_4;
	management_rf_res  close_rf_res_101_arg;
	enum clnt_stat retval_5;
	int result_5;
	data_rf_res  write_rf_res_101_arg;
	enum clnt_stat retval_6;
	int result_6;
	data_rf_res  read_rf_res_101_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, REMOTE_FIFO, CLIENT_API, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = create_rf_res_101(&create_rf_res_101_arg, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = unlik_rf_res_101(&unlik_rf_res_101_arg, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = open_rf_res_101(&open_rf_res_101_arg, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_4 = close_rf_res_101(&close_rf_res_101_arg, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_5 = write_rf_res_101(&write_rf_res_101_arg, &result_5, clnt);
	if (retval_5 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_6 = read_rf_res_101(&read_rf_res_101_arg, &result_6, clnt);
	if (retval_6 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	remote_fifo_1 (host);
	remote_fifo_101 (host);
exit (0);
}
